services:
  - type: web
    name: omegle-backend
    env: node
    buildCommand: npm install && npm run install-server
    startCommand: npm run start-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; connect-src 'self' wss: ws: https: http: *; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src 'self' blob: mediastream:; img-src 'self' blob: data:;"
      - path: /socket.io/*
        name: Content-Security-Policy
        value: "default-src 'self'; connect-src 'self' wss: ws: https: http: *;"
    routes:
      - type: rewrite
        source: /socket.io/*
        destination: /socket.io/$1
