services:
  - type: web
    name: omegle-backend
    env: node
    buildCommand: npm install && npm run install-server
    startCommand: npm run start-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /socket.io/*
        destination: /socket.io/$1
